# Generated by Django 4.2 on 2023-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия клиента')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('basket', models.TextField(verbose_name='Корзина товаров')),
            ],
        ),
    ]
