# Generated by Django 6.0.6 on 2026-06-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=200, verbose_name='Фото товару'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Унікальна назва'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.TextField(verbose_name='Корзина товарів'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Им'я клієнта"),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Прізвище клієнта'),
        ),
    ]
